apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: bloghub
  labels:
    app: user-service
    tier: backend
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 3003
    protocol: TCP
    name: http
  selector:
    app: user-service

